#!/usr/bin/env bash

# Add user Shotengai

sudo useradd -m shotengai
sudo usermod -aG sudo shotengai
sudo passwd -e shotengai

# Install Shotengai Dependencies

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e
log_info() {
  printf "\n\e[0;35m $1\e[0m\n\n"
}

if [ ! -f "$HOME/.bashrc" ]; then
  touch $HOME/.bashrc
fi

log_info "Updating Packages ..."
  sudo apt-get update

log_info "Installing Git ..."
  sudo apt-get -y install git

log_info "Installing build essentials ..."
  sudo apt-get -y install build-essential

log_info "Installing libraries for common gem dependencies ..."
  sudo apt-get -y install libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libreadline-dev libssl-dev zlib1g-dev libsnappy-dev

log_info "Installing Postgres ..."
  sudo apt-get -y install postgresql postgresql-server-dev-all postgresql-contrib libpq-dev

log_info "Installing curl ..."
  sudo apt-get -y install curl

if [ ! "$(convert -version)" &> /dev/null ]; then
  log_info "Installing ImageMagick ..."
    sudo apt-get -y install libtool
    wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/install-imagemagick
    chmod +x install-imagemagick
    sudo ./install-imagemagick
fi

log_info "Installing image utilities ..."
  sudo apt-get -y install advancecomp gifsicle jpegoptim libjpeg-progs optipng pngcrush pngquant
  sudo apt-get -y install jhead

log_info "Installing make ..."
  sudo apt-get -y install make

if [[ ! -d "$HOME/.rbenv" ]]; then
  log_info "Installing rbenv ..."
    git clone https://github.com/rbenv/rbenv.git ~/.rbenv

    if ! grep -qs "rbenv init" ~/.bashrc; then
      printf 'export PATH="$HOME/.rbenv/bin:$PATH"\n' >> ~/.bashrc
      printf 'eval "$(rbenv init - --no-rehash)"\n' >> ~/.bashrc
      source ~/.bashrc
    fi

    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

if [[ ! -d "$HOME/.rbenv/plugins/ruby-build" ]]; then
  log_info "Installing ruby-build, to install Rubies ..."
    git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
fi

log_info "Installing Ruby 2.7.2 ..."
  rbenv install 2.7.2

log_info "Setting 2.7.2 as global default Ruby ..."
  rbenv global 2.7.2
  rbenv rehash

log_info "Installing Rails 6.0.2 ..."
  gem install rails -v 6.0.2

log_info "Installing Bundler 2.2.15 ..."
  gem install bundler:2.2.15 --no-rdoc --no-ri
  gem env home
  rbenv rehash

if [ ! -x "$(command -v docker)" ]; then
  log_info "Installing Docker ..."
    curl https://get.docker.com/ | sh
  log_info "Avoid typing sudo ..."
    source ~/.bashrc
    sudo usermod -aG docker ${USER}
    sudo usermod -aG docker shotengai
fi
